## CareerLens AI EDA

### Data Exploration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
df = pd.read_csv('data/career_dataset_10k.csv')
df.head()

,user_id,education,experience_years,skills,interests,certification,target_career
0,c8322c2a,MBA,5,"['product management', 'business', 'excel']",['business'],NaN,Product Manager
1,c1349484,BSc,8,"['ui/ux', 'nodejs', 'cybersecurity', 'java']",['web development'],Google Data Analytics,Backend Developer
2,ea49041b,MCA,4,"['seo', 'html']",['marketing'],AWS Certification,Digital Marketer
3,f4240d3e,BTech,3,"['react', 'tableau']",['web development'],Azure Fundamentals,Web Developer
4,34981705,MCA,1,"['nodejs', 'sql', 'excel']",['web development'],Azure Fundamentals,Backend Developer

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10000 non-null  str
 1   education         10000 non-null  str
 2   experience_years  10000 non-null  int64
 3   skills            10000 non-null  str
 4   interests         10000 non-null  str
 5   certification     8333 non-null   str
 6   target_career     10000 non-null  str
dtypes: int64(1), str(6)
memory usage: 547.0 KB

In [4]:
df.describe(include='all')

,user_id,education,experience_years,skills,interests,certification,target_career
count,10000,10000,10000.000000,10000,10000,8333,10000
unique,10000,6,NaN,7582,7,5,9
top,c8322c2a,BSc,NaN,"['machine learning', 'data analysis', 'sql', '...",['ai'],AWS Certification,Data Scientist
freq,1,1735,NaN,23,2809,1689,1214
mean,NaN,NaN,5.077500,NaN,NaN,NaN,NaN
std,NaN,NaN,3.167696,NaN,NaN,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,2.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,8.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,10.000000,NaN,NaN,NaN,NaN

In [5]:
# Check for missing values
df.isna().sum()

user_id                0
education              0
experience_years       0
skills                 0
interests              0
certification       1667
target_career          0
dtype: int64

In [7]:
df = df.drop(['user_id'],axis=1)
df.head()

,education,experience_years,skills,interests,certification,target_career
0,MBA,5,"['product management', 'business', 'excel']",['business'],NaN,Product Manager
1,BSc,8,"['ui/ux', 'nodejs', 'cybersecurity', 'java']",['web development'],Google Data Analytics,Backend Developer
2,MCA,4,"['seo', 'html']",['marketing'],AWS Certification,Digital Marketer
3,BTech,3,"['react', 'tableau']",['web development'],Azure Fundamentals,Web Developer
4,MCA,1,"['nodejs', 'sql', 'excel']",['web development'],Azure Fundamentals,Backend Developer

In [8]:
# Classification of columns into cat and num
cat_cols = df.select_dtypes(include='object').columns
num_cols = df.select_dtypes(include=['int','float']).columns
print(f"Categorical Columns: {cat_cols}")
print(f"Numerical Columns: {num_cols}")

# Unique values in cat columns
for col in cat_cols:
    print(f"{col}: {df[col].unique()[:5]}...")
    print(f"Value Counts: \n{df[col].value_counts()}")
    print("="*50)

Categorical Columns: Index(['education', 'skills', 'interests', 'certification', 'target_career'], dtype='str')
Numerical Columns: Index(['experience_years'], dtype='str')
education: <StringArray>
['MBA', 'BSc', 'MCA', 'BTech', 'Diploma']
Length: 5, dtype: str...
Value Counts:
education
BSc        1735
BCA        1672
BTech      1666
MCA        1649
Diploma    1649
MBA        1629
Name: count, dtype: int64
==================================================
skills: <StringArray>
[ '['product management', 'business', 'excel']',
 '['ui/ux', 'nodejs', 'cybersecurity', 'java']',
                              '['seo', 'html']',
                         '['react', 'tableau']',
                   '['nodejs', 'sql', 'excel']']
Length: 5, dtype: str...
Value Counts:
skills
['machine learning', 'data analysis', 'sql', 'python']                                 23
['networking', 'cybersecurity']                                                        20
['nodejs', 'sql', 'java']                                                              19
['css', 'javascript', 'react', 'html']                                                 16
['aws', 'cloud computing', 'azure']                                                    16
                                                                                       ..
['cybersecurity', 'react', 'ui/ux', 'machine learning', 'deep learning', 'nodejs']      1
['aws', 'product management', 'java', 'deep learning', 'excel', 'sql']                  1
['digital marketing', 'html', 'machine learning', 'python', 'data analysis', 'sql']     1
['cloud computing', 'sql', 'excel', 'seo']                                              1
['c++', 'figma', 'tableau', 'html', 'ui/ux', 'deep learning']                           1
Name: count, Length: 7582, dtype: int64
==================================================
interests: <StringArray>
['['business']', '['web development']', '['marketing']', '['ai']', '['data']']
Length: 5, dtype: str...
Value Counts:
interests
['ai']                 2809
['web development']    2148
['business']           1125
['design']             1119
['marketing']          1111
['security']           1064
['data']                624
Name: count, dtype: int64
==================================================
certification: <StringArray>
[                    nan, 'Google Data Analytics',     'AWS Certification',
    'Azure Fundamentals',           'Coursera ML']
Length: 5, dtype: str...
Value Counts:
certification
AWS Certification        1689
Azure Fundamentals       1689
Google Data Analytics    1667
Udemy Web Dev            1653
Coursera ML              1635
Name: count, dtype: int64
==================================================
target_career: <StringArray>
[  'Product Manager', 'Backend Developer',  'Digital Marketer',
     'Web Developer',    'Cloud Engineer']
Length: 5, dtype: str...
Value Counts:
target_career
Data Scientist           1214
Product Manager          1125
ML Engineer              1120
UI/UX Designer           1119
Digital Marketer         1111
Cloud Engineer           1099
Web Developer            1080
Backend Developer        1068
Cybersecurity Analyst    1064
Name: count, dtype: int64
==================================================